import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
// import { Provider } from "@/utils/Provider";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} my-5 h-full bg-amber-50 dark:bg-slate-950 text-indigo-950 dark:text-amber-50 dark:selection:bg-purple-500`}>
        <ThemeProvider attribute="class">
          <Navbar />
          <main className="mx-auto max-w-5xl px-6">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
