import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Provider } from "@/utils/Provider";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} h-full bg-amber-200 dark:bg-slate-700`}>
        <Provider>
          <Navbar />
          <main className="mx-auto max-w-5xl px-6">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
